### ISSUE TITLE
Possible to use with memory mapped IO between two processes ?

### ISSUE THREAD

**Issue by stuaxo** [chainreactionmfg/cara#3]
I guess mmap + capnproto between two processes must be about as fast as you can get, is it possible with cara ?

**Comment by fahhem** [comment]
cara itself doesn't do anything in regards to serialization, beyond supporting msgpack natively.

If you use pseud, then you can take advantage of zmq's ipc transport. It's not memory-mapped, but it's very efficient nonetheless.

You're welcome to use any RPC layer, and any de/serialization layer that it supports. I haven't looked for new RPC layers in a while, but I'm sure new ones have popped up that handle memory mapping for IPC.
